name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - run: nix build .#dockerImages.x86_64-linux.default
